apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Este es el nombre del role
  name: portainer-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - namespaces
    verbs:
      - get
      - list
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
